// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UcneGuideApi.DAL;

#nullable disable

namespace UcneGuideApi.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250327020355_DatosDeIngenieriaEnSistemas")]
    partial class DatosDeIngenieriaEnSistemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UcneGuideApi.DAL.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UcneGuideApi.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("UcneGuideApi.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("UcneGuideApi.Models.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            MateriaId = 1,
                            CarreraId = 1,
                            Codigo = "HUM-111",
                            Descripcion = "Muy buen",
                            Nombre = "Lengua Española y Técnica de Expresión I",
                            ProfesorId = 1
                        },
                        new
                        {
                            MateriaId = 2,
                            CarreraId = 1,
                            Codigo = "MAT-125",
                            Descripcion = "Muy buen",
                            Nombre = "Precalculo",
                            ProfesorId = 2
                        },
                        new
                        {
                            MateriaId = 3,
                            CarreraId = 1,
                            Codigo = "HUM-123",
                            Descripcion = "Muy buen",
                            Nombre = "Filosofía",
                            ProfesorId = 3
                        },
                        new
                        {
                            MateriaId = 4,
                            CarreraId = 1,
                            Codigo = "QMA-117",
                            Descripcion = "Muy buen",
                            Nombre = "Química I",
                            ProfesorId = 4
                        },
                        new
                        {
                            MateriaId = 5,
                            CarreraId = 1,
                            Codigo = "QMA-118",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio de Química I",
                            ProfesorId = 5
                        },
                        new
                        {
                            MateriaId = 6,
                            CarreraId = 1,
                            Codigo = "FIS-136",
                            Descripcion = "Muy buen",
                            Nombre = "Física I",
                            ProfesorId = 6
                        },
                        new
                        {
                            MateriaId = 7,
                            CarreraId = 1,
                            Codigo = "FIS-137",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio Física I",
                            ProfesorId = 7
                        },
                        new
                        {
                            MateriaId = 8,
                            CarreraId = 1,
                            Codigo = "ORI-116",
                            Descripcion = "Muy buen",
                            Nombre = "Orientación Académica",
                            ProfesorId = 8
                        },
                        new
                        {
                            MateriaId = 9,
                            CarreraId = 1,
                            Codigo = "HUM-121",
                            Descripcion = "Muy buen",
                            Nombre = "Lengua Española y Técnica de Expresión II",
                            ProfesorId = 9
                        },
                        new
                        {
                            MateriaId = 10,
                            CarreraId = 1,
                            Codigo = "FIS-230",
                            Descripcion = "Muy buen",
                            Nombre = "Física II",
                            ProfesorId = 10
                        },
                        new
                        {
                            MateriaId = 11,
                            CarreraId = 1,
                            Codigo = "FIS-231",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio Física II",
                            ProfesorId = 11
                        },
                        new
                        {
                            MateriaId = 12,
                            CarreraId = 1,
                            Codigo = "MAT-140",
                            Descripcion = "Muy buen",
                            Nombre = "Cálculo Diferencial",
                            ProfesorId = 12
                        },
                        new
                        {
                            MateriaId = 13,
                            CarreraId = 1,
                            Codigo = "ISC-201",
                            Descripcion = "Muy buen",
                            Nombre = "Introducción a la Ingeniería en Sistemas",
                            ProfesorId = 13
                        },
                        new
                        {
                            MateriaId = 14,
                            CarreraId = 1,
                            Codigo = "ISC-202",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio Introducción a la Ingeniería en Sistemas",
                            ProfesorId = 14
                        },
                        new
                        {
                            MateriaId = 15,
                            CarreraId = 1,
                            Codigo = "ISC-203",
                            Descripcion = "Muy buen",
                            Nombre = "Estructuras Discretas",
                            ProfesorId = 15
                        },
                        new
                        {
                            MateriaId = 16,
                            CarreraId = 1,
                            Codigo = "ISC-204",
                            Descripcion = "Muy buen",
                            Nombre = "Doctrina Social de la Iglesia",
                            ProfesorId = 16
                        },
                        new
                        {
                            MateriaId = 17,
                            CarreraId = 1,
                            Codigo = "ISC-205",
                            Descripcion = "Muy buen",
                            Nombre = "Calculo Integral",
                            ProfesorId = 17
                        },
                        new
                        {
                            MateriaId = 18,
                            CarreraId = 1,
                            Codigo = "MAT-141",
                            Descripcion = "Muy buen",
                            Nombre = "Fisica III",
                            ProfesorId = 18
                        },
                        new
                        {
                            MateriaId = 19,
                            CarreraId = 1,
                            Codigo = "ISC-206",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio de Fisica III",
                            ProfesorId = 19
                        },
                        new
                        {
                            MateriaId = 20,
                            CarreraId = 1,
                            Codigo = "ISC-207",
                            Descripcion = "Muy buen",
                            Nombre = "Tecnica de Programacion",
                            ProfesorId = 20
                        },
                        new
                        {
                            MateriaId = 21,
                            CarreraId = 1,
                            Codigo = "ISC-208",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio de Tecnica de Programacion",
                            ProfesorId = 21
                        },
                        new
                        {
                            MateriaId = 22,
                            CarreraId = 1,
                            Codigo = "ISC-209",
                            Descripcion = "Muy buen",
                            Nombre = "Actividad Cocurricular",
                            ProfesorId = 22
                        },
                        new
                        {
                            MateriaId = 23,
                            CarreraId = 1,
                            Codigo = "ISC-210",
                            Descripcion = "Muy buen",
                            Nombre = "Educacion En Valores",
                            ProfesorId = 23
                        },
                        new
                        {
                            MateriaId = 24,
                            CarreraId = 1,
                            Codigo = "ISC-211",
                            Descripcion = "Muy buen",
                            Nombre = "Metodologia de la Investigacion",
                            ProfesorId = 24
                        },
                        new
                        {
                            MateriaId = 25,
                            CarreraId = 1,
                            Codigo = "ISC-212",
                            Descripcion = "Muy buen",
                            Nombre = "Contabilidad General",
                            ProfesorId = 25
                        },
                        new
                        {
                            MateriaId = 26,
                            CarreraId = 1,
                            Codigo = "ISC-213",
                            Descripcion = "Muy buen",
                            Nombre = "Calculo Vectorial",
                            ProfesorId = 26
                        },
                        new
                        {
                            MateriaId = 27,
                            CarreraId = 1,
                            Codigo = "ISC-214",
                            Descripcion = "Muy buen",
                            Nombre = "Programacion I",
                            ProfesorId = 27
                        },
                        new
                        {
                            MateriaId = 28,
                            CarreraId = 1,
                            Codigo = "ISC-215",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio de Programacion I",
                            ProfesorId = 28
                        },
                        new
                        {
                            MateriaId = 29,
                            CarreraId = 1,
                            Codigo = "ISC-216",
                            Descripcion = "Muy buen",
                            Nombre = "Estructura de Datos",
                            ProfesorId = 29
                        },
                        new
                        {
                            MateriaId = 30,
                            CarreraId = 1,
                            Codigo = "ISC-217",
                            Descripcion = "Muy buen",
                            Nombre = "Ecologia y preservacion del medio ambiente",
                            ProfesorId = 30
                        },
                        new
                        {
                            MateriaId = 31,
                            CarreraId = 1,
                            Codigo = "ISC-218",
                            Descripcion = "Muy buen",
                            Nombre = "Algebra Lineal",
                            ProfesorId = 31
                        },
                        new
                        {
                            MateriaId = 32,
                            CarreraId = 1,
                            Codigo = "ISC-219",
                            Descripcion = "Muy buen",
                            Nombre = "Electronica Aplicada",
                            ProfesorId = 32
                        },
                        new
                        {
                            MateriaId = 33,
                            CarreraId = 1,
                            Codigo = "ISC-220",
                            Descripcion = "Muy buen",
                            Nombre = "Analisis de sistemas",
                            ProfesorId = 33
                        },
                        new
                        {
                            MateriaId = 34,
                            CarreraId = 1,
                            Codigo = "ISC-221",
                            Descripcion = "Muy buen",
                            Nombre = "Programacion II",
                            ProfesorId = 34
                        },
                        new
                        {
                            MateriaId = 35,
                            CarreraId = 1,
                            Codigo = "ISC-222",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio de Programacion II",
                            ProfesorId = 35
                        },
                        new
                        {
                            MateriaId = 36,
                            CarreraId = 1,
                            Codigo = "ISC-223",
                            Descripcion = "Muy buen",
                            Nombre = "Sistemas Operativos",
                            ProfesorId = 36
                        },
                        new
                        {
                            MateriaId = 37,
                            CarreraId = 1,
                            Codigo = "ISC-224",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorios Sistemas Operativos",
                            ProfesorId = 37
                        },
                        new
                        {
                            MateriaId = 38,
                            CarreraId = 1,
                            Codigo = "ISC-225",
                            Descripcion = "Muy buen",
                            Nombre = "Principios de seguridad informatica",
                            ProfesorId = 38
                        },
                        new
                        {
                            MateriaId = 39,
                            CarreraId = 1,
                            Codigo = "ISC-226",
                            Descripcion = "Muy buen",
                            Nombre = "Probabilidad y estadistica",
                            ProfesorId = 39
                        },
                        new
                        {
                            MateriaId = 40,
                            CarreraId = 1,
                            Codigo = "ISC-227",
                            Descripcion = "Muy buen",
                            Nombre = "Base de Datos I",
                            ProfesorId = 40
                        },
                        new
                        {
                            MateriaId = 41,
                            CarreraId = 1,
                            Codigo = "ISC-228",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio Base de Datos I",
                            ProfesorId = 41
                        },
                        new
                        {
                            MateriaId = 42,
                            CarreraId = 1,
                            Codigo = "ISC-229",
                            Descripcion = "Muy buen",
                            Nombre = "Arquitectura del Computador",
                            ProfesorId = 42
                        },
                        new
                        {
                            MateriaId = 43,
                            CarreraId = 1,
                            Codigo = "ISC-230",
                            Descripcion = "Muy buen",
                            Nombre = "Programacion III",
                            ProfesorId = 43
                        },
                        new
                        {
                            MateriaId = 44,
                            CarreraId = 1,
                            Codigo = "ISC-231",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio Programacion III",
                            ProfesorId = 44
                        },
                        new
                        {
                            MateriaId = 45,
                            CarreraId = 1,
                            Codigo = "ISC-232",
                            Descripcion = "Muy buen",
                            Nombre = "Ecuaciones Diferenciales",
                            ProfesorId = 45
                        },
                        new
                        {
                            MateriaId = 46,
                            CarreraId = 1,
                            Codigo = "ISC-233",
                            Descripcion = "Muy buen",
                            Nombre = "Diseño de Sistemas",
                            ProfesorId = 46
                        },
                        new
                        {
                            MateriaId = 47,
                            CarreraId = 1,
                            Codigo = "ISC-234",
                            Descripcion = "Muy buen",
                            Nombre = "Proyecto Aplicado",
                            ProfesorId = 47
                        },
                        new
                        {
                            MateriaId = 48,
                            CarreraId = 1,
                            Codigo = "ISC-235",
                            Descripcion = "Muy buen",
                            Nombre = "Mantenimiento del Hadware",
                            ProfesorId = 48
                        },
                        new
                        {
                            MateriaId = 49,
                            CarreraId = 1,
                            Codigo = "ISC-236",
                            Descripcion = "Muy buen",
                            Nombre = "Teleproceso y Redes",
                            ProfesorId = 49
                        },
                        new
                        {
                            MateriaId = 50,
                            CarreraId = 1,
                            Codigo = "ISC-237",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio de teleproceso y redes",
                            ProfesorId = 50
                        },
                        new
                        {
                            MateriaId = 51,
                            CarreraId = 1,
                            Codigo = "ISC-238",
                            Descripcion = "Muy buen",
                            Nombre = "Programacion Aplicada I",
                            ProfesorId = 51
                        },
                        new
                        {
                            MateriaId = 52,
                            CarreraId = 1,
                            Codigo = "ISC-239",
                            Descripcion = "Muy buen",
                            Nombre = "Laboratorio Programacion Aplicada I",
                            ProfesorId = 52
                        },
                        new
                        {
                            MateriaId = 53,
                            CarreraId = 1,
                            Codigo = "ISC-241",
                            Descripcion = "Muy buen",
                            Nombre = "Pasantia I",
                            ProfesorId = 53
                        },
                        new
                        {
                            MateriaId = 54,
                            CarreraId = 1,
                            Codigo = "ISC-242",
                            Descripcion = "Muy buen",
                            Nombre = "Ingenieria Econimica",
                            ProfesorId = 53
                        },
                        new
                        {
                            MateriaId = 55,
                            CarreraId = 1,
                            Codigo = "ISC-243",
                            Descripcion = "Muy buen",
                            Nombre = "Organizacion y Administracion de sistemas",
                            ProfesorId = 53
                        },
                        new
                        {
                            MateriaId = 56,
                            CarreraId = 1,
                            Codigo = "ISC-244",
                            Descripcion = "Muy buen",
                            Nombre = "Base de Datos II",
                            ProfesorId = 53
                        },
                        new
                        {
                            MateriaId = 57,
                            CarreraId = 1,
                            Codigo = "ISC-245",
                            Descripcion = "Muy buen",
                            Nombre = "laboratorio de Base de Datos II",
                            ProfesorId = 53
                        },
                        new
                        {
                            MateriaId = 58,
                            CarreraId = 1,
                            Codigo = "ISC-246",
                            Descripcion = "Muy buen",
                            Nombre = "Programacion Aplicada I",
                            ProfesorId = 53
                        },
                        new
                        {
                            MateriaId = 59,
                            CarreraId = 1,
                            Codigo = "ISC-247",
                            Descripcion = "Muy buen",
                            Nombre = "Computacion Centrada en Redes",
                            ProfesorId = 53
                        },
                        new
                        {
                            MateriaId = 60,
                            CarreraId = 1,
                            Codigo = "ISC-248",
                            Descripcion = "Muy buen",
                            Nombre = "Simulacion Digital",
                            ProfesorId = 53
                        });
                });

            modelBuilder.Entity("UcneGuideApi.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("UcneGuideApi.Models.Sugerencia", b =>
                {
                    b.Property<int>("SugerenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SugerenciaId");

                    b.ToTable("Sugerencias");
                });

            modelBuilder.Entity("UcneGuideApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UcneGuideApi.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UcneGuideApi.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UcneGuideApi.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UcneGuideApi.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
